# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e26526573e4df5aa871f0dd7dd77ceefea4010d8d7dbfb04c7dad5e61d2cea79d7d7a6c40c7f1cbb19f8b3f17013547004d8a231596ebef4ade0cc1ee36ec020

test:
  secret_key_base: 0b6a10959fed218975d28f55e182d90d646aaa07f37465bceb005e622b5ae1eddbf64016de422059cca07f5774244e06b06fac80ded17e45248baa582b047258

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
